export const questionsArray = [
  "If you could be invisible for a day, what’s the first thing you would do?",
  "What’s the biggest secret you’ve kept from your parents?",
  "What’s the most embarrassing music you listen to?",
  "What’s one thing you love most about yourself?",
  "Who is your secret crush?",
  "Who is the last person you creeped on social media?",
  "When was the last time you wet the bed?",
  "If a genie granted you three wishes, what would you ask for and why?",
  "What’s your biggest regret?",
  "If you had to only ever watch rom-coms or only watch scary movies for the rest of your life, which would you choose and why?",
  "Where is the weirdest place you've ever gone to the bathroom?",
  "Have you ever ghosted on someone?",
  "Which player would survive a zombie apocalypse and which would be the first to go?",
  "Reveal all the details of your first kiss.",
  "What excuse have you used before to get out plans?",
  "What's the longest you've ever slept?",
  "What’s the shortest you’ve ever slept?",
  "Read the last text you sent your best friend or significant other out loud.",
  "What's your biggest pet peeve?",
  "When was the last time you lied?",
  "What five things would you bring to a deserted island?",
  "Which is your favorite Hollywood Chris? Chris Evans, Chris Pratt, Chris Hemsworth or Chris Pine?",
  "What's the most embarrassing thing you ever did on a date?",
  "What is the boldest pickup line you've ever used?",
  "What celebrity do you think you most look like?",
  "How many selfies do you take a day?",
  "What is one thing you would stand in line an hour for?",
  "When was the last time you cried?",
  "What's the longest time you've ever gone without showering?",
  "What's the most embarrassing top-played song on your phone?",
  "What was your favorite childhood show?",
  "If you had to change your name, what would your new first name be?",
  "If you could be a fictional character for a day, who would you choose?",
  "If you could date a fictional character, who would it be?",
  "What's your biggest fear?",
  "What's one silly thing you can't live without?",
  "Where was your favorite childhood vacation spot?",
  "What is the weirdest trend you've ever participated in?",
  "If you could only listen to one song for the rest of your life, what would you choose?",
  "Who do you text the most?",
  "Have you ever been fired from a job?",
  "If you had to wear only flip-flops or heels for the next 10 years, which would you choose?",
  "What’s an instant deal breaker in a potential love interest?",
  "If you could only eat one thing for the rest of your life, what would you choose?",
  "What is the biggest lie you ever told your parents?",
  "What's the worst physical pain you've ever experienced?",
  "Which player knows you the best?",
  "What's your favorite part of your body?",
  "If you could only accomplish three things in life, what would they be?",
  "What's the weirdest thing you've ever eaten?",
  "Have you ever gone skinny dipping?",
  "Tell us about the biggest romantic fail you’ve ever experienced.",
  "Who was your first celebrity crush?",
  "What's the strangest dream you've ever had?",
  "What are the top three things you look for in a love interest?",
  "What is your worst habit?",
  "How many stuffed animals do you own?",
  "Do you sleep with any stuffed animals?",
  "What is your biggest insecurity?",
  "Name one thing you’d do if you knew there’d be zero consequences.",
  "When’s the last time you said you were sorry? For what?",
  "Do you pee in the shower?",
  "Do you still have feelings for any of your exes?",
  "What’s the most embarrassing thing you’ve done to get a crush’s attention?",
  "What’s the most random thing in your bag right now?",
  "Have you ever sent a sext?",
  "What’s the last movie that made you cry?",
  "What’s the last song that made you cry?",
  "What are the five most recent things in your search history?",
  "When’s the last time you got caught in a lie?",
  "What gross smell do you actually enjoy?",
  "Who was the last person you said “I love you” to?",
  "Have you ever had a paranormal experience?",
  "If you could have lunch with a famous person, dead or alive, who would you pick and why?",
  "If you were handed $1,000 right now, what would you spend it on?",
  "Who’s your celebrity “hall pass” if you were to meet that person while in a relationship?",
  "Have you ever cheated on an exam?",
  "What unexpected part of the body do you find attractive?",
  "What’s the most awkward thing you’ve ever been caught doing?",
  "Have you ever flirted with a close friend’s sibling?",
  "What was your first concert?",
  "If you had the choice to never have to sleep again, would you take it?",
  "If you had to get a tattoo today, what would it be?",
  "Even if you’d be paid $1 million for it, what’s something you would never do?",
  "If you could travel to the past and meet one person, who would it be?",
  "What popular TV show or movie do you secretly hate?",
  "Where do you see yourself in 10 years?",
  "Name your go-to karaoke song.",
  "What’s the most adventurous thing you’ve ever done?",
  "When have you been in the most trouble in school?",
  "If you had to always be overdressed or underdressed, which would you choose?",
  "Who would you cast as you and your friends in the movie version of your life?",
  "What’s the luckiest thing that’s ever happened to you?",
  "Do you have any phobias?",
  "Do you believe in an afterlife?",
  "If you had to move to a different country tomorrow, where would you go?",
  "What do you want to be remembered for most in life?",
  "Do you believe in soul mates?",
  "Have you ever re-gifted a present? What was it?",
  "What’s the weirdest thing you do when you’re alone?",
  "What movie (or franchise) are you most embarrassed to love?",
  "Have you ever had an imaginary friend? Describe them.",
  "What gross food combo do you secretly love?",
  "If you could become besties with a celebrity, who would it be?",
  "What’s the most embarrassing nickname you’ve ever been given?",
  "If you could trade lives with any person you know for a day, who would it be?",
  "What’s the worst thing you’ve ever said to anyone?",
  "What’s the scariest dream you’ve ever had?",
  "What’s the weirdest place you’ve kissed/hooked up with someone?",
  "Have you ever slid into a celebrity’s DMs?",
  "What superstitions do you believe in?",
  "Are you Team Edward or Team Jacob (or both?)",
  "What app do you check first in the morning?",
  "What’s the most embarrassing thing you’ve ever purchased?",
  "What’s the longest you’ve ever gone without brushing your teeth?",
  "What’s the weirdest thing you have in your bedroom?",
  "What’s the weirdest thing you have in your locker?",
  "How often do you wash your sheets?",
  "Do you sing in the shower? What was the last song you belted out?",
  "What’s the weirdest thing you do while driving?",
  "Have you ever started a rumor about someone? What was it?",
  "If you could talk to a fortune teller, what would you ask them?",
  "Do you believe in aliens? What do you think they look like?",
  "Have you ever given a fake number?",
  "What’s more important to you: love or money?",
  "Is there anyone you stalk on social media?",
  "What's the most memorable lesson you learned from your parents?",
  "Who are you jealous of?",
  "Have you ever been rejected by someone?",
  "Have you ever fallen in love at first sight?",
  "Do you want to get married someday?",
  "What are you most excited about at this very moment?",
  "What’s your wildest fantasy?",
  "What do you write about the most in your diary?",
  "Are you afraid of the future?",
  "Have you ever been in a fight?",
  "Have you ever ditched someone before?",
  "Have you ever had a wardrobe malfunction?",
  "Have you ever intentionally sabotaged someone?",
  "Have you ever lied to a friend?",
  "Have you ever said “I love you” to someone and not meant it?",
  "If I went through your cabinets, what’s the weirdest thing I’d find?",
  "How have your priorities changed over time?",
  "If you suddenly had a million dollars, how would you spend it?",
  "Is there an ex with whom you’d consider reconciling?",
  "Name one thing you’d do if you knew there’d be zero consequences.",
  "Personality-wise, are you more like your mom or your dad?",
  "What are you most proud of in your life?",
  "What bridges are you glad that you burned?",
  "What do you think happens when you die?",
  "What was your biggest childhood fear?",
  "What was your first heartbreak?",
  "What’s the biggest mistake you’ve ever made?",
  "What’s something you’re glad your mom doesn’t know about you?",
  "What’s the worst thing anyone’s ever done to you?",
  "What’s been your most physically painful experience?",
  "What’s something you know you need to do but aren’t looking forward to at all?",
  "What’s something you only do when you’re alone?",
  "What was the best compliment you’ve ever received?",
  "What’s the scariest thing that’s ever happened to you?",
  "What’s your favorite possession?",
  "When was the last time you apologized? What for?",
  "Would you marry someone rich even if you weren’t in love with them?",
  "Have you ever fallen out of love?",
  "Name one childish thing that you still do.",
  "Have you ever let someone else take the blame for something you have done?",
  "What is the stupidest thing you have done for a crush or partner?",
  "What are the things you think about while sitting on the toilet?",
  "How far are you willing to go for the person of your dreams?",
  "What is something stupid you have done to try to be ‘cooler’?",
  "Who was your first love?",
  "If you were stranded on an island, who would you want to be stranded with?",
  "What is your dream career?",
  "What is the strangest thing you have ever bought?",
  "What makes you the happiest?",
  "What does falling in love feel like to you?",
  "Do you think you’re a good person?",
  "What are the elements of the perfect day?",
  "Do you believe it’s ok to have secrets in a relationship?",
  "If you saw a friend’s partner cheating, would you tell the friend? Why or why not?",
  "Do you trust people easily?",
  "If you could switch lives with someone for a day, who would it be and why?",
  "What's the most adventurous thing on your bucket list?",
  "If you could have a meal with any historical figure, who would it be, and what would you ask them?",
  "Have you ever had a supernatural experience or encountered something you couldn't explain?",
  "If you could time travel to any era in history, where and when would you go?",
  "What's your go-to dance move when nobody's watching?",
  "If you could learn any new skill instantly, what would it be?",
  "What's the most unusual or exotic food you've ever tried, and did you like it?",
  "If you had the power to instantly solve one global problem, what would it be?",
  "What's your favorite way to unwind and relax after a long day?",
  "If you could have a conversation with your future self, what advice would you ask for?",
  "What's the most valuable lesson you've learned from a past relationship?",
  "If you could be a character in any fictional world, which one would you choose?",
  "What's your hidden talent that most people don't know about?",
  "If you could visit any place on Earth, real or fictional, where would you go?",
  "What's the most bizarre or unusual job you can think of that you'd like to try for a day?",
  "If you could have any animal as a loyal pet, even mythical ones, what would it be?",
  "What's the most challenging thing you've ever accomplished, and how did it change you?",
  "If you could meet and spend a day with any living celebrity, who would it be, and what would you do together?",
  "What's your favorite way to make someone smile or laugh when they're having a bad day?",
  "If you could instantly speak and understand any language, which one would you choose?",
  "What's the most breathtaking natural wonder you'd like to witness in person?",
  "If you were a character in a book, movie, or TV show, what would your catchphrase be?",
  "What's the most unexpected or random act of kindness you've ever experienced?",
  "If you could go on a cross-country road trip with any three people, living or deceased, who would they be?",
  "What's the most extreme sport or adventure activity you'd be willing to try?",
  "If you could have dinner with any fictional character, who would it be, and what would you talk about?",
  "What's the strangest or most unique tradition your family has?",
  "If you had the ability to instantly learn any musical instrument, which one would you choose to master?",
  "What's your favorite way to spread positivity and kindness in the world?",
  "If you could possess any superpower, but only one, what would it be and how would you use it?",
  "What's the most valuable piece of advice you've received from a family member or close friend?",
  "If you were a famous author, what genre of books would you write, and what would your pen name be?",
  "What's the most unusual or unique tradition you'd like to start with your friends or family?",
  "If you could attend any event in history, like a famous concert or speech, which one would it be?",
  "What's the most memorable dream or nightmare you've ever had?",
  "If you could have dinner with any fictional villain, who would it be, and what would you ask them?",
  "What's your favorite way to give back to your community or make a positive impact on the world?",
  "If you could have a personal theme song that played whenever you entered a room, what would it be?",
  "What's the most beautiful place in nature you've ever visited, and how did it make you feel?",
  "If you could spend a day in the life of an animal, which one would you choose, and why?",
  "What's your guilty pleasure when it comes to TV shows, movies, or music?",
  "If you could instantly acquire a new hobby or skill, unrelated to your current interests, what would it be?",
  "What's the most heartwarming act of kindness you've witnessed from a stranger?",
  "If you could have a conversation with a famous artist, musician, or writer, who would it be, and what would you discuss?",
  "What's the most fascinating historical era, event, or figure you'd like to know more about?",
  "If you could eliminate one chore or daily task from your life forever, what would it be?",
  "What's the most valuable lesson you've learned from a difficult experience or failure?",
  "If you could teleport to any place in the world right now, where would you go, and what would you do?",
  "What's your favorite thing about a rainy day?",
  "If you could have any animal ability, such as flying like a bird or swimming like a dolphin, what would you choose?",
  "What's the most incredible or breathtaking natural phenomenon you'd like to witness?",
  "If you could have a conversation with a character from a book you've read, who would it be, and what would you ask them?",
  "What's the most impressive or unique talent you've seen someone else possess?",
  "If you could travel back in time and give your younger self one piece of advice, what would it be?",
  "What's the most unusual food combination you enjoy that others might find strange?",
  "If you could attend a fictional school, like Hogwarts or Xavier's School for Gifted Youngsters, which one would it be, and why?",
  "What's your favorite thing about the changing of seasons?",
];
